apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-eployment
  labels:
    app: nginx
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: flask 
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container 
        image: abdelrahman1993/testflask 
        ports:
        - containerPort: 5000 
